[project]
name = "flyingmanbo"
version = "1.0.1"
description = "FlyingManbo by Kjulam"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
]

[project.scripts]
flyingmanbo = "__main__:main"
