[project]
name = "FlyingManbo"
version = "1.0.1"
description = "A game called FlyingManbo by Kjulam"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
]

[project.scripts]
flying-manbo = "__main__:main"
